language: java
jdk:
  - openjdk8

script: ./mvnw clean install


jobs:
  include:
    - stage: Test
      script: 
             - chmod +x mvnw
             - ./mvnw clean test
             - ./mvnw verify -Pprod -DskipTests

notification:
  email: dayanacogaria@gmail.com
